
server:
  port: 8082
## mybatis-plus configuration info
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # logically-deleted value(default is 1)
      logic-not-delete-value: 0 # logically  un deleted value(default is 0)
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.andey.mbplus.dao

## mysql configuration info
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&autoReconnect=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mmyy12345
Spring:
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 2000